USE [master]
GO

/****** Object:  Database [SalotDB]    Script Date: 07/04/2022 22.40.35 ******/
CREATE DATABASE [SalotDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ReeniDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\ReeniDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'ReeniDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\ReeniDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SalotDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [SalotDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [SalotDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [SalotDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [SalotDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [SalotDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [SalotDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [SalotDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [SalotDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [SalotDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [SalotDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [SalotDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [SalotDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [SalotDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [SalotDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [SalotDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [SalotDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [SalotDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [SalotDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [SalotDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [SalotDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [SalotDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [SalotDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [SalotDB] SET RECOVERY FULL 
GO

ALTER DATABASE [SalotDB] SET  MULTI_USER 
GO

ALTER DATABASE [SalotDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [SalotDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [SalotDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [SalotDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [SalotDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [SalotDB] SET QUERY_STORE = OFF
GO

USE [SalotDB]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE [SalotDB] SET  READ_WRITE 
GO


